### ISSUE TITLE
item entity repository 및 서브타입들을 생성한다.

### ISSUE THREAD

**Issue by kwakmins** [kawkmin/Ego-Board#13]
## 📝 Description

item 관련 entity repository를 생성합니다.
상속관계 매핑을 사용하여, Item을 슈퍼타입으로 지정한 후, 서브타입(shoes, clothes, hat)을 생성합니다.

## ☑️ TODO

- [x] item entity를 생성합니다.
- [x] item repository를 생성합니다.
- [x] 서브타입(shoes, clothes, hat)을 생성합니다.
