### ISSUE TITLE
User Entity, Repository를 생성한다.

### ISSUE THREAD

**Issue by kwakmins** [kawkmin/Ego-Board#3]
## 📝 Description

User Entity, Repository를 생성합니다.

## ☑️ TODO

- [x] 임베디드인 address를 생성 및 구현합니다.
- [x] User Entity를 생성합니다.
- [x] User Repository를 생성합니다.
