### ISSUE TITLE
Post Entity,Repository를 생성한다.

### ISSUE THREAD

**Issue by kwakmins** [kawkmin/Ego-Board#7]
## 📝 Description

Post Entity,Repository를 생성합니다.

## ☑️ TODO

- [x] 게시판 임베디드인, board를 생성 및 구현합니다.
- [x] Post Entity를 생성합니다.
- [x] Post Repository를 생성합니다.
